### ISSUE TITLE
Multiple Reports concatenating variables between them

### ISSUE THREAD

**Issue by anomaly0617** [HandyGuySoftware/dupReport#103]
Hi handyguy,

I’m having a problem with running dupReport.py multiple times in one session. For instance, I have a bash script set up that does the following:

/dupReport/testrun.sh
#!/bin/bash
/dupReport/dupReport.py -r /dupReport/rc/location1
/dupReport/dupReport.py -r /dupReport/rc/location2
/dupReport/dupReport.py -r /dupReport/rc/location3
/dupReport/dupReport.py -r /dupReport/rc/location4
/dupReport/dupReport.py -r /dupReport/rc/location5

… and a crontab file that looks like this:
0 07 * * 1-5 /dupReport/dupReport.py -r /dupReport/rc/location1
0 13 * * 1-5 /dupReport/dupReport.py -r /dupReport/rc/location2
0 13 * * 1-5 /dupReport/dupReport.py -r /dupReport/rc/location3
0 13 * * 1-5 /dupReport/dupReport.py -r /dupReport/rc/location4
0 13 * * 1-5 /dupReport/dupReport.py -r /dupReport/rc/location5

The script (above) is used for me to test what backup reports look like before they are put into production and end-users get the reports.

The crontab (below) is how I’d like to run them once they are in production.

Thankfully, I’m the only one getting the emails right now. Otherwise, I’d have a really big problem.

The output of both scenarios above generates 5 emails.

The first email looks perfect.
The second email contains the data for the first location and then the data for the second.
The third email contains the data for the first through third locations.
The fourth email contains the data for the first through fourth locations
The fifth email contains the data for the first through fifth locations
(… and a partridge in a pear treeeee)

So, it’s obvious that the do-while or for-x-to-y statement is running an append on a variable in the script that contains the output. The problem is, at the end of each script, the variables don’t appear to be getting cleared.

Is this an easy fix?

Thanks!
-Paul

**Comment by HandyGuySoftware** [comment]
OK, interesting. Some random thoughts/questions to start with:

1. You specify -r on the command line for different .RC files, but do you use different databases for each backup job (using dbpath=) in the .rc file? Using one db for all jobs might start to explain some of the confusion.
2. What is different in each of the .RC files? Is it just the mail server used or are there multiple options that are different?
3. Even though you aren't there yet, running locations 2-5 at the same time ("0 13") may be an issue. dR is not designed for concurrency and SQLIte (that dR uses) doesn't handle it well, either. Unless you're using a different db for each location (question #1 above) you may see some issues. 
4. Can you post (or attach) images of what the reports look like? Sometimes a visual is easier to comprehend than a description.

Anyway, that's a start. Let me know the answers to these and we can continue trying to narrow down the problem.

**Comment by HandyGuySoftware** [comment]
@anomaly0617 , just checking to see if this is still a problem for you and what we can do to help figure out what's happening.

HG

**Comment by anomaly0617** [comment]
Ok, so some answers!

1. The fix was 100% moving the database and log files to their respective /dupReport/rc/location{x} folders. Immediately resolved the issue.

2. The only major differences between the files is a) who the email goes to and b) what folder in the IMAP connector it looks to for backup results. I have Exchange rules to move them based on the email address they are coming from. Otherwise, they are pretty much identical.

3. Good call, but not necessary once I discovered #1 fixed it.

4. Assuming I run into this again, I’ll be happy to send out screenshots. Admittedly I’m customizing the output (report.py) to tailor the email to make it more appealing to less technical eyes. :-)

**Comment by HandyGuySoftware** [comment]
Customizing the reports are fine. I'd be interested in seeing what you come up with, as it may be useful for other users as well!
