### ISSUE TITLE
Invalid Character Causes Crash

### ISSUE THREAD

**Issue by chbeck2010** [HandyGuySoftware/dupReport#110]
Recently had to do a bit of troubleshooting. One of my backups failed and I rebuilt the database (which also failed) but did send an email that dupReport attempted to parse. Causing it to crash. (I lost the actual error from dupreport. But I am attaching the offending email (after I deleted it dup report worked again. Not 100% sure on how you have it implemented but you should be able to test/handle invalid characters or use try/catch on a per email processing basis and if one email throws and exception. Just abandon that email (and log it) and move on to the next one without killing dup report.

[Gmail - Duplicati Backup report for Charles_Office>Charles_SFTP--accept-any-ssl-certificate=P.pdf](https://github.com/HandyGuySoftware/dupReport/files/2800903/Gmail.-.Duplicati.Backup.report.for.Charles_Office.Charles_SFTP--accept-any-ssl-certificate.P.pdf)
[Send_To_Developer_dupReport.log](https://github.com/HandyGuySoftware/dupReport/files/2800904/Send_To_Developer_dupReport.log)

**Comment by chbeck2010** [comment]
Because I realized I wasn't being very helpful without the original error and exception I moved the email back to my dupreport folder and reran to get the error again. So here is the exception that causes dupReport to crash. The fix is easy enough. (Delete the bad email) But wanted to share in case you want to catch it in code instead of crashing.

C:\Scripts\DupReport>c:\Python36\python.exe C:\Scripts\DupReport\dupReport.py
Connecting to email servers.
Analyzing email messages.
.............................................................................................................................Traceback (most recent call last):
  File "C:\Scripts\DupReport\dupReport.py", line 240, in <module>
    nxtMsg = globs.inServer.processNextMessage()
  File "C:\Scripts\DupReport\dremail.py", line 401, in processNextMessage
    globs.log.write(3, 'Message Body=[{}]'.format(msgBody))
  File "C:\Scripts\DupReport\log.py", line 88, in write
    logTarget.write(msg)
  File "c:\Python36\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 2824-2826: character maps to undefined

**Comment by HandyGuySoftware** [comment]
@chbeck2010, 

Thanks for the report. What version of dupReport are you running? We had very similar error reported recently that was fixed on version 2.2.5, which is available on the pre_prod branch. Please download and run that version to see if it addresses the problem. If not, make sure you use the -v3 option to get a full log file and post that file so I can take a look. 

Also, what are you using for a mail server (e.g., Gmail, exchange, etc.) and are you using IMAP or POP3?

HG

**Comment by HandyGuySoftware** [comment]
@chbeck2010 just checking to see if the latest beta version (2.2.5) resolved the problem you were having. I'm getting ready to release it to production, so if there's still work we need to do please let me know.

HG

**Comment by chbeck2010** [comment]
I was on 2.2.1 but updated to 2.2.4 after getting the error. I just tried ofter updating to 2.2.5 and it seems to have been resolved. Thanks

**Comment by HandyGuySoftware** [comment]
Good to hear, thanks for confirming. You should be able to pull the released 2.2.5 from the master branch in a couple of days.

Thanks,

HG
