### ISSUE TITLE
Request: Mark emails as "read" after being processed

### ISSUE THREAD

**Issue by Taomyn** [HandyGuySoftware/dupReport#111]
Can dupReport mark the emails as “read” once processed?

I use IMAP on my own mail server and can see the dedicated mailbox on my normal client, but all the emails remain unread. It would be nice if dupReport marked each as read once it had processed them. Also simple way to know that all is still well.

**Comment by HandyGuySoftware** [comment]
Taomyn,

I added a "markread" option in the [main] section of the .rc file. Set it to true and the program will mark your emails as read on the server once they have been processed. The code can be found in the "Issue_111" branch. If you can download that branch and see if it works for you that would be great.

Thanks,

HG

**Comment by Taomyn** [comment]
HG, thanks, I've downloaded the files and will give it a try later today.

**Comment by Taomyn** [comment]
FYI, the new code worked, it marked all the previous emails as read - I'd like to give it one more automatic run tonight to be 100% but it looks good to me. Cheers.

**Comment by HandyGuySoftware** [comment]
Sounds good. Let me know if the next run works. If so, I still need to add a couple of tweaks to it and I'll upload it to the pre_prod branch for everyone to test out. Thanks for helping to test this.

**Comment by Taomyn** [comment]
It ran just fine, great job.

**Comment by HandyGuySoftware** [comment]
Added to 2.2.6.
