### ISSUE TITLE
dupReport.rc-> Incoming-> infolder gives error with non-default folder

### ISSUE THREAD

**Issue by axiomcs78** [HandyGuySoftware/dupReport#117]
C:\dupReport-master>c:\python37\python dupReport.py

C:\dupReport-master>c:\python37\python dupReport.py
Traceback (most recent call last):
  File "dupReport.py", line 232, in <module>
    newMessages = globs.inServer.checkForMessages()
  File "C:\dupReport-master\dremail.py", line 206, in checkForMessages
    retVal, data = self.server.search(None, "ALL")
  File "c:\python37\lib\imaplib.py", line 723, in search
    typ, dat = self._simple_command(name, *criteria)
  File "c:\python37\lib\imaplib.py", line 1196, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "c:\python37\lib\imaplib.py", line 944, in _command
    ', '.join(Commands[name])))
imaplib.error: command SEARCH illegal in state AUTH, only allowed in states SELECTED

C:\dupReport-master>

**Comment by HandyGuySoftware** [comment]
@axiomcs78, please run the program with the -v3 option and post the resulting log file. That will help trace what's happening.

**Comment by axiomcs78** [comment]
******** dupReport Log - Start: Fri May 24 10:16:33 2019
Program Version 2.2.6 Release
Database Version 1.0.2
Python version 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
initOptions()
Processing command line...
options.processCmdLineArgs()
Command line parsed:
- rcpath = [None]
- dbpath = [None]
- logpath = [None]
- verbose = [3]
- Version = [False]
- append = [False]
- size = [None]
- initdb = [False]
- rollback = [None]
- rollbackx = [None]
- file = [None]
- nomail = [False]
- remove = [None]
- purgedb = [False]
- stopbackupwarn = [False]
- collect = [False]
- report = [False]
- masksensitive = [False]
- nomasksensitive = [False]
RC path not specified on command line. Using default.
Final RC path=[********************************]
options.openRcFile(********************************)
options.checkRcFileVersion()
RC file versions: current=226 new=210.
Current version number=226. Need to upgrade rc file? False
options.setRcDefaults()
rc.setDefaults(********************************)
newRc=False
options.readRcOptions(********************************)
Parsed config option [rcfilename]=[********************************]
Parsed config option [version]=[False]
Parsed config option [dbpath]=[********************************]
Parsed config option [logpath]=[*********************************]
Parsed config option [verbose]=[3]
Parsed config option [logappend]=[False]
Parsed config option [subjectregex]=[^Duplicati Backup report for]
Parsed config option [srcregex]=[\w*]
Parsed config option [destregex]=[\w*]
Parsed config option [srcdestdelimiter]=[-]
Parsed config option [dateformat]=[MM/DD/YYYY]
Parsed config option [timeformat]=[HH:MM:SS]
Parsed config option [warnoncollect]=[False]
Parsed config option [applyutcoffset]=[True]
Parsed config option [show24hourtime]=[True]
Parsed config option [purgedb]=[False]
Parsed config option [showprogress]=[0]
Parsed config option [masksensitive]=[True]
Parsed config option [markread]=[False]
Parsed config option [intransport]=[imap]
Parsed config option [inserver]=[**************]
Parsed config option [inport]=[993]
Parsed config option [inencryption]=[none]
Parsed config option [inaccount]=[********************]
Parsed config option [inpassword]=[***********]
Parsed config option [infolder]=[AtoZ]
Parsed config option [inkeepalive]=[False]
Parsed config option [outserver]=[**************]
Parsed config option [outport]=[587]
Parsed config option [outencryption]=[tls]
Parsed config option [outaccount]=[******************]
Parsed config option [outpassword]=[****************]
Parsed config option [outsender]=[******************************]
Parsed config option [outreceiver]=[**********************************]
Parsed config option [outkeepalive]=[False]
Parsed config option [collect]=[False]
Parsed config option [report]=[False]
Parsed config option [nomail]=[False]
Parsed config option [remove]=[None]
Parsed config option [stopbackupwarn]=[False]
Parsed config option [rollback]=[None]
Parsed config option [rollbackx]=[None]
Parsed config option [initdb]=[False]
Parsed config option [file]=[None]
Need to restart? False
Program initialization complete. Continuing program.
Database.__init__(********************************)
Database.checkDbVersion()
Database.execSqlStmt(): Executing SQL command.
SQL stmt=[SELECT major, minor, subminor FROM version WHERE desc = 'database']
Database: current version=102  new version=102
Logfile=[*********************************]  appendlog=[False]  logLevel=[3]
dbPath=[********************************]  rcpath=[********************************]
Database.execSqlStmt(): Executing SQL command.
SQL stmt=[UPDATE emails SET dbSeen = 0]
Database.dbCommit(): Committing transaction.
EmailServer.Connect()
server=None keepalive=False
Initial connect using  IMAP
IMAP Logged in. retVal=OK data=*
IMAP Setting folder. retVal=NO data=[b'[NONEXISTENT] Unknown Mailbox: AtoZ (Failure)']
checkForMessages(IMAP)

Here is my relevant incoming from dupReport.rc
[incoming]
intransport = imap
inserver = imap.gmail.com
inport = 993
inencryption = none
inaccount = ********@gmail.com
inpassword = ********
infolder = AtoZ
inkeepalive = false

And my email folders:
https://i.gyazo.com/a852489e2f656315a08d076646c4f1db.png

**Comment by dcurrey** [comment]
Thant looks like the same error you get with an incorrect mailbox.

Since this is a subfolder should it be listed as Inbox/AtoZ or Inbox.AtoZ.   (Not sure how python handles subfolder I am sure handyguy will have the correct answer)

**Comment by axiomcs78** [comment]
Proper results were obtained with Inbox/AtoZ (Inbox.AtoZ produced the same error).

**Comment by HandyGuySoftware** [comment]
Sorry to be late, been traveling the past couple of days. If your tag (Gmail's name for a folder) was a top-level tag (i.e., at the same level as Inbox) your original specification would have worked. Since it was a subfolder, specifying it as a path (as @dcurrey noted) gives the proper spec for dupReport to find it. 

Python's IMAP library treats the email repositories as paths so subfolders should be separated by a '/' character. I'm not sure if there is a limit to the number of subfolders you can have,

Thanks @dcurrey for stepping in to solve this one!
