### ISSUE TITLE
Duplicati version in the “Backup Sets Last Seen” table

### ISSUE THREAD

**Issue by HandyGuySoftware** [HandyGuySoftware/dupReport#121]
from @Taomyn:

One small request: could the Duplicati version also appear in the “Backup Sets Last Seen” table at the start? Would make it easier to check, plus when no backup log was processed for a machine it doesn’t appear in the main summary report table.

https://forum.duplicati.com/t/announcing-dupreport-a-duplicati-email-report-summary-generator/1116/98

**Comment by Taomyn** [comment]
Thanks, I'll remember to post requests directly here on Github from now on to save you the work.

**Comment by HandyGuySoftware** [comment]
I have uploaded new code to the "Issue_121" branch. Try it out to see if that's what you were looking for in the "Last Seen" table.

**Comment by Taomyn** [comment]
That's perfect than-you very much.

![image](https://user-images.githubusercontent.com/4365929/60320175-2e656400-9979-11e9-8aa7-4b0fcf544563.png)
