### ISSUE TITLE
Do We Still need Source-Destination Pairs?

### ISSUE THREAD

**Issue by HandyGuySoftware** [HandyGuySoftware/dupReport#132]
Discussion Topic: Should Source-Destination Pairs still be a thing in dupReport?

Hi folks. I’ve been kicking around the idea of a dupReport upgrade/rewrite (version 3.0.0?) and one of the things I’ve been considering is dropping the requirement that backup jobs be named in the \<Source>-\<Destination> format. I’m not entirely sure yet how that would work, but I’d thought I’d poll the users and get their feedback on the following questions:

- Does the S-D naming format cause problems for you?
- Would your backup jobs (and subsequent reporting) be better if dupReport didn’t require S-D job naming?
- Do you have any suggestions on what the output reports might look like if they weren’t ordered/sorted by S-D pairs?
- Any other comments you’d like to share on the concept?
 
I’m really interested in hearing everyone’s thoughts on the topic before investing what will be a lot of time unwravelling the S-D format in dupReport.

**Comment by Taomyn** [comment]
- Does the S-D naming format cause problems for you?
**Nope**
- Would your backup jobs (and subsequent reporting) be better if dupReport didn’t require S-D job naming?
**I don't think it would, I like naming standards and using this forced me to keep to them.**
- Do you have any suggestions on what the output reports might look like if they weren’t ordered/sorted by S-D pairs?
**Not really**
- Any other comments you’d like to share on the concept?
**Nope**

**Comment by mr-flibble** [comment]
I think that _Source-Destination Pairs system_ is ideal, easy to implement and well-arranged so I vote not change it: )

**Comment by dcurrey** [comment]
I see no reason to change it.

If required maybe something as simple as an alias in the [source-destination] section
```
[mysource-mydest]
alias = My Backup
nobackupwarn = 3
nbwsubject = BACKUP WARNING: #SOURCE##DELIMITER##DESTINATION# not being backed up!
receiver = person@mailserver.com
```

**Comment by HandyGuySoftware** [comment]
Overwhelming response was to keep the S-D format. Other suggested features were given their own issue.

**Comment by HandyGuySoftware** [comment]
@dcurrey ,  can you expand more on how the alias would be used? Would you like to see the alias used in the final report instead of the S-D pair name or is there some other use I'm not thinking of?

**Comment by dcurrey** [comment]
I am fine with the original setup.   

Someone might want something a different in final reports.   A simple Source-Destination alias replacement in final report should cover this.

**Comment by HandyGuySoftware** [comment]
Sounds good. I'm in the code now so I might just throw it in. Can't have too many features! ;-)

Thanks,

HG
