### ISSUE TITLE
Visualization/Graphics

### ISSUE THREAD

**Issue by HandyGuySoftware** [HandyGuySoftware/dupReport#133]
From mr-flibble:

> But regarding version 3.0, did you consider some kind visualization/graphing ? There are many libraries for python, for example Example Gallery — Altair 4.0.0 documentation
> Having some kind generated images in report would certainly be very useful

**Comment by mr-flibble** [comment]
> Would you be willing to go there to add some more explanation on what type of graphics might be helpful? Is there anything you’ve seen elsewhere that might be a good fit?

Hello, thank you for creating issue:)
it might be useful to see backup time and backup size ? For example this is from https://www.duplicati-monitoring.com/
![image](https://user-images.githubusercontent.com/5197625/74566564-0bbda500-4f74-11ea-8948-7de7c22cb3da.png)

For short term - what I want to see in weekly report is, if there was some mayor change, for example rapid storage increase ...this is pain to see in current html only report :)

**Comment by HandyGuySoftware** [comment]
Deferred. Taking too much time for 3.0 and not sure how to make it generic & configurable enough to be useful. Will pick this up again in the future.
