### ISSUE TITLE
Remove requirement for 'import apprise' 

### ISSUE THREAD

**Issue by jrwrigh** [HandyGuySoftware/dupReport#153]
Current (version 3.0.0) implementation requires that apprise be importable, otherwise the script will error out. 

Previously (version 2.2.12), the `import apprise` was only launched when the dupApprise class was initialized.
https://github.com/HandyGuySoftware/dupReport/blob/908d1c0c28ac0c470b242f37cc6632bc5c132369/dupapprise.py#L19-L27

Now (version 3.0.0) it is always imported when `dupApprise.py` is imported:
https://github.com/HandyGuySoftware/dupReport/blob/d3b3c5fd5c3f4660d2d73c6b702222caac5bf6af/dupapprise.py#L12-L20

Either the `import apprise` should be moved back into the class initialization or a try except should be added for it's import (or the import of `dupApprise.py`) where an error is only raised if the `dupReport.rc` requests using apprise.

**Comment by HandyGuySoftware** [comment]
That's what happens when I update code that I don't use all that often ;-) I just pushed a test release under the [Issue_153_154 Branch](https://github.com/HandyGuySoftware/dupReport/tree/Issue_153_154). Please download that and see if it fixes the issue.

**Comment by jrwrigh** [comment]
Ok, so now that I can actually run version 3.0.0, I had to go through the entire setup process again, and now it does work.

**Comment by HandyGuySoftware** [comment]
Apologies for that. Thanks for the quick test. Let me know if you have any other issues.
