### ISSUE TITLE
dupReport.py installer changes folder name

### ISSUE THREAD

**Issue by jirijanata** [HandyGuySoftware/dupReport#163]
Hello,

I just installed dupReport 3.0.2. I'm using Gmail for Duplicati Report emails and all emails are automatically moved to the Duplicati folder in the Gmail.

I installed dupReport using dupReport.py and I also entered to the command line the folder name - Duplicati
`Please enter the IMAP folder name to where Duplicati emails are stored on the 'incoming' server [INBOX]: Duplicati`

But in the generated dupReport.rc was the folder name changed to DUPLICATI and then I got following error:
`Traceback (most recent call last):
  File "C:\Users\Username\AppData\Local\dupReport\dupReport.py", line 131, in <module>
    globs.emailManager.checkForNewMessages()
  File "C:\Users\Username\AppData\Local\dupReport\dremail.py", line 141, in checkForNewMessages
    newMessages = self.incoming[server].checkForMessages()
  File "C:\Users\Username\AppData\Local\dupReport\dremail.py", line 364, in checkForMessages
    retVal, data = self.serverconnect.search(None, scope)
  File "C:\Program Files\Python39\lib\imaplib.py", line 734, in search
    typ, dat = self._simple_command(name, *criteria)
  File "C:\Program Files\Python39\lib\imaplib.py", line 1230, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "C:\Program Files\Python39\lib\imaplib.py", line 968, in _command
    raise self.error("command %s illegal in state %s, "
imaplib.error: command SEARCH illegal in state AUTH, only allowed in states SELECTED`

I changed the name in the dupReport.rc back to Duplicati and it works now fine.

**Working**
> [incoming]
protocol = imap
server = imap.gmail.com
port = 993
encryption = tls
account = myemail@gmail.com
password = password
folder = Duplicati
keepalive = false
unreadonly = false
markread = false
authentication = basic

**Generated with dupReport.py and not working**
> [incoming]
protocol = imap
server = imap.gmail.com
port = 993
encryption = tls
account = myemail@gmail.com
password = password
folder = DUPLICATI
keepalive = false
unreadonly = false
markread = false
authentication = basic

I'm using Python 3.9.1 x64 on the Windows Server 2016.

**Comment by HandyGuySoftware** [comment]
Issue cause by incorrect conversion to uppercase when folder name is read from user. Fixed and uploaded in Release 3.0.3.

**Comment by jirijanata** [comment]
Thank you, I tried it and it works just fine.
