### ISSUE TITLE
Only send on failure 

### ISSUE THREAD

**Issue by binaryfire** [HandyGuySoftware/dupReport#173]
Hello

Great project! Is it possible to only send email reports if backups fail?

Cheers

**Comment by HandyGuySoftware** [comment]
Hi @binaryfire , thanks for the suggestion. 

I have thought several times about adding this very feature, but have never done so for the following reason. Enabling such a feature would mean that you would only get email if one (or more) of your jobs fail. However, not getting an email would not be a guarantee that everything was working properly. For example:

1. The backup job could have crashed before completing
2. Duplicati could have failed or crashed without running the backup job
3. dupReport could have failed or crashed before completing

All of these would mean you would not receive an email about a failed backup job, but that would not be a good thing. You would never know that something was wrong with your system(s). For this reason, dupReport always sends an email, even if everything worked properly. Not receiving an email from dupReport is a sign that something is wrong and needs to be checked out.

However, there is a way to get close to what you are looking for. There is an option in the [report] section of the .rc file:
`failedonly = false`
If this is set to "true" it instructs dupReport to only include backup jobs in the report that have a "warning" or "failed" result status. So, you would still get an emailed report, but it would be a short one that only included failed jobs. There is a sample report section in the dupreport.rc.EXAMPLE file called [failedonly] that does just that.

This would allow you to get the best of both worlds: the email letting you know that dupReport ran successfully but the report would show only failed jobs.

I hope this helps. Thanks for using dupReport.

HG
