### ISSUE TITLE
Enabling "Less secure apps" is required for Gmail access

### ISSUE THREAD

**Issue by ekutner** [HandyGuySoftware/dupReport#175]
This is really a documentation suggestion.
Beyond the regular Gmail settings to allow IMAP access it is also necessary allow access for "_Less secure apps_" in the account security management page. Without this setting dupReport fails to access both IMAP and SMTP because it is being denied by Google with an unhelpful message "invalid credentials". 
It would be a good idea to suggest using a dedicated gmail account just for the backup reports and not enable this setting on accounts that are used for other purposes.

**Comment by HandyGuySoftware** [comment]
@ekutner , this is a good suggestion. I will add it to the next release of the software. Thanks.

HG

**Comment by HandyGuySoftware** [comment]
Added to 3.0.7.
