### ISSUE TITLE
Need to handle different date/time formats

### ISSUE THREAD

**Issue by yakox** [HandyGuySoftware/dupReport#19]
It looks like the date and time formats in the Duplicati email reports vary depending on locale. I have the following formats:

This one is OK:
EndTime: 11/4/2017 12:03:26 PM
BeginTime: 11/4/2017 11:58:16 AM

This one fails with exception:
EndTime: 04/11/2017 14:33:58
BeginTime: 04/11/2017 14:31:00

Probably many ways to handle that. The attached version works for me this moment.

[dupReport.zip](https://github.com/HandyGuySoftware/dupReport/files/1443328/dupReport.zip)

**Comment by HandyGuySoftware** [comment]
yakox,

This was also reported by another user yesterday. Please pull down branch 2.0.3_Issue_18 and see if that works for you. If so, I can push that fix into the master branch.

**Comment by HandyGuySoftware** [comment]
But, that opens up another issue I didn't anticipate - the euro dd/mm/yy format as opposed to the US mm/dd/yy format. Need to debug that one as well. Can you let me know what your locale settings are on your system?

**Comment by yakox** [comment]
Interestingly the 2 report formats both come from machines with the same Windows settings (en-GB). Admittedly one is in UK and one is in Spain so I am not sure where Duplicati gets the time format from.

![image](https://user-images.githubusercontent.com/8077577/32407119-1c8582e6-c17c-11e7-9059-ab2f01f33fca.png)

As you say, dd/mm/yyyy is hard to distinguish from mm/dd/yyyy for days <= 12. To make it explicitly configurable would mean e.g. defining a default and allowing an override per backup set..

I see there are some related discussions for Duplicati:  [https://github.com/duplicati/duplicati/issues/2753](url)

**Comment by HandyGuySoftware** [comment]
Yeah, date/time/locale issues in Duplicati have been a recurring theme on the forums. I can set an rc file option to define which one should be used, but that would be global for all backup sets. DupReport doesn't see the source/destination pairs until they come in the emails, so it would be hard to predefine them on a per-set basis. I'll see if I can code up the global configuration this weekend so you can test it out. Any work on more fine-grained configuration will need to wait for 2.1.  Work on that will start soon, but there are a lot of changes planned for that release, so it may be a while before a beta is available.

**Comment by HandyGuySoftware** [comment]
yakox,

I have pushed a new version to the 2.0.3_Issue_18 branch. Running the program will create a 'dateformat' option in the [main] section of the .rc file. The default is US-style dates, but you can then edit the .rc file and change 'us' to 'euro'. This will force dR to recognize DD/MM/YYYY format from emails. As discussed, this is a global value that is the same for all incoming emails. I am adding a feature request for 2.1 that will allow for changing that value for specific S/D pairs.

Since I don't have euro dates on any of my systems I have no way of testing this in the real world. If you can run the program through your emails and let me know how it goes, that would be greatly appreciated.

**Comment by HandyGuySoftware** [comment]
yakox,

The old code still didn't work, so new (hopefully fixed) code uploaded to Issue_18 branch. To test it, do the following:

1. In your dupReport.rc file, delete the 'dateformat' option from the [main] section.
2. Run the program. It will error out telling you telling you the RC file needs configuration.
3. Edit the RC file, adjusting the new 'dateformat' option in [main]. The acceptable formats are in the README file included in the branch.
4. Run the program again and let me know if it fixes the date parsing issues.

Hopefully this is the one. If not, .... well let's not think about that right now. :-)

Also, we're discussing the same problem in the thread for Issue #21. You might want to join that discussion as well.

**Comment by yakox** [comment]
Apologies for the delay - I have tried the Issue_18 branch and it seems to do the trick for this issue.

**Comment by HandyGuySoftware** [comment]
Good to hear, glad it helped. You should download the 'master' branch, since that has this fix and a few others.

Also, I've opened up a Twitter account: @dupreport. You can follow that to get future update announcements.
