### ISSUE TITLE
Change default report to show MB

### ISSUE THREAD

**Issue by davegold24** [HandyGuySoftware/dupReport#22]
Enhancement request: Change default report to show MB. 

The announcement page shows "Size(MB)" and "+/-(MB)", but that isn't showing up in my output version.
Original posting picture.
![image](https://user-images.githubusercontent.com/31834856/32416081-32a2a6f4-c211-11e7-88aa-4b8807efac3a.png)

My output with version 2.0.3 using defaults shows:
![image](https://user-images.githubusercontent.com/31834856/32416063-04baa9b2-c211-11e7-9712-472a9100cea2.png)
If using bytes, it should show "bytes".

Also some add'l thoughts, let me know if you want me to open a separate issue for this one:
Could I suggest the following columns (separated by commands for clarity only:
Date;Time;Protected Files Count;  Files Count changing during Job ; Protected Size (MB); Size change during job; Add files; Deleted files; Modified files; Errors; Job Result

Also, if you can use a two layer table:
Overall Stats versus Job Stats would be interesting.

--Dave

**Comment by HandyGuySoftware** [comment]
The 'MB/GB' only shows if you set the sizereduce option to 'mega' or 'giga'. If sizereduce is set to 'none' you get the full byte count for any size column.

I'll add the column headings as a separate issue. I tried to keep the titles short, but there may be a way to optionally include longer titles.
