### ISSUE TITLE
Background on table cell

### ISSUE THREAD

**Issue by TowerBR** [HandyGuySoftware/dupReport#24]
Hello HandyGuy, I made a small change, see if you find it interesting: a highlight in the lines with the names of the jobs. When you have a lot of small backups, I found the report look a bit confusing, so I put a background in the line with the names. Look:

![old](https://user-images.githubusercontent.com/33122168/32547991-3483b632-c46b-11e7-981f-4944d18624da.png)

![new](https://user-images.githubusercontent.com/33122168/32547997-3b9690c0-c46b-11e7-9edb-2193e655c8da.png)

I just put the color tag here (line 690):

    msgHtml = msgHtml + '<td bgcolor="#E6E6E6" align="center" colspan = "11"><b>{}</b></td>'.format(txt[0])

( BTW: Do you prefer this type of post here or in the Duplciati forum? )

**Comment by HandyGuySoftware** [comment]
Added to the 2.1 features list.

Either location is fine, I check both.

**Comment by HandyGuySoftware** [comment]
Added to version 2.1
