### ISSUE TITLE
Problem with Czech characters in email message

### ISSUE THREAD

**Issue by mr-flibble** [HandyGuySoftware/dupReport#26]
Hello, sorry for new problem:)

I'm getting this error message (bellow) because one email with czech characters ("ř" or "í" )
```
Traceback (most recent call last):
  File "B:\Dulezite_Programy_universal\dupReport_PortablePython3.2.5.1_IS_config\dupReport.py", line 1053, in <module>
    send_email()
  File "B:\Dulezite_Programy_universal\dupReport_PortablePython3.2.5.1_IS_config\dupReport.py", line 728, in send_email
    server.sendmail(options['outsender'], options['outreceiver'], msg.as_string())
  File "B:\Dulezite_Programy_universal\dupReport_PortablePython3.2.5.1_IS_config\App\lib\smtplib.py", line 735, in sendmail
    msg = _fix_eols(msg).encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 909-910: ordinal not in range(128)
```
![image](https://user-images.githubusercontent.com/5197625/33205075-e825816a-d105-11e7-967e-744dbd03068b.png)

**This is mail causing problems:**
```
DeletedFiles: 0
DeletedFolders: 0
ModifiedFiles: 26
ExaminedFiles: 34909
OpenedFiles: 28
AddedFiles: 0
SizeOfModifiedFiles: 17731452928
SizeOfAddedFiles: 0
SizeOfExaminedFiles: 88587088695
SizeOfOpenedFiles: 17731452928
NotProcessedFiles: 0
AddedFolders: 0
TooLargeFiles: 0
FilesWithError: 2
ModifiedFolders: 0
ModifiedSymlinks: 0
AddedSymlinks: 0
DeletedSymlinks: 0
PartialBackup: False
Dryrun: False
MainOperation: Backup
ParsedResult: Error
VerboseOutput: False
VerboseErrors: False
EndTime: 23.11.2017 23:25:34
BeginTime: 23.11.2017 23:00:00
Duration: 00:25:33.6594762
Messages: [
    No remote filesets were deleted
]
Warnings: [
    Failed to process metadata for "x.ldf", storing empty metadata => (5) Přístup byl odepřen: [\\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy18\x.ldf],
    Failed to process path: x => (5) Přístup byl odepřen: [\\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy18\x.ldf],
    Failed to process metadata for "x.mdf", storing empty metadata => (5) Přístup byl odepřen: [\\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy18\x.mdf],
    Failed to process path: x.mdf => (5) Přístup byl odepřen: [\\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy18\x.mdf]
]
Errors: []
```

**I found workaround - if i change:**
old value  **msg = _fix_eols(msg).encode('ascii')**
to   **msg = _fix_eols(msg).encode('utf-8')**
in file ..\App\Lib\smtplib.py

![image](https://user-images.githubusercontent.com/5197625/33205848-ac491b40-d108-11e7-8c8c-53f6d9ed7184.png)

then reporting is working ok*

But I don't know is this is best practice :-)

**Comment by HandyGuySoftware** [comment]
mr-flibble,

No trouble at all. It's not the best form to alter the base Python libraries, as that may alter behavior for other programs that use the same library. 

Debugging this may be difficult, as I don't have any Czech emails to test with. However, I have done some research and ask the following:

First back out the fix you did in smtp.lib.py, by returning the line back to:

> msg = _fix_eols(msg).encode('ascii')

Then, in line 728 of dupReport.py, change it to the following:

> server.sendmail(options['outsender'], options['outreceiver'], msg.as_string().encode('utf-8'))

Try that and see if it fixes your problem. Let me know what happens.

**Comment by mr-flibble** [comment]
HI!
Thanks for fast reply, I just tested it and it works flawlessly :-) 

Do you plan include utf-8 line in future releases, or I should remember to change it after every update ?

Thank you:)

**Comment by HandyGuySoftware** [comment]
I'll need to test it on the 2.1 code now in development to make sure it doesn't break anything else. If it checks out I'll add it to 2.1 (and forward) release.
