### ISSUE TITLE
2.1.0 DB out of date error 

### ISSUE THREAD

**Issue by mr-flibble** [HandyGuySoftware/dupReport#35]
Hello, after upgrade to 2.1 beta, I get this error message.

Nothing in log file
Config is automatically updated 

```
*** Remote Interpreter Reinitialized  ***
>>> 
Database file B:\Dulezite_Programy_universal\dupReport_PortablePython3.2.5.1/dupReport.db is out of date. Needs update to latest version.
Traceback (most recent call last):
  File "B:\Dulezite_Programy_universal\dupReport_PortablePython3.2.5.1\dupReport.py", line 138, in <module>
    canContinue = initOptions()
  File "B:\Dulezite_Programy_universal\dupReport_PortablePython3.2.5.1\dupReport.py", line 91, in initOptions
    globs.log.out(1, 'Need to upgrade database {} from version {} to version {}{}{}'.format(globs.opts['dbpath'], currDbVersion, globs.dbVersion[0], globs.dbVersion[1], globs.dbVersion[2]))
TypeError: out() takes exactly 2 positional arguments (3 given)
>>> 
```

![image](https://user-images.githubusercontent.com/5197625/33769779-bc0b48ae-dc2b-11e7-93da-95d2bdc54a31.png)

**Workaround for this message is dupReport.py -i - after the error is no longer displayed**

**Comment by HandyGuySoftware** [comment]
globs.log.out() does not take the integer argument at the beginning. This was changed from a globs.log.write() which does take an initial integer (the logging level).

Fixed.
