### ISSUE TITLE
-c option broken

### ISSUE THREAD

**Issue by dcurrey** [HandyGuySoftware/dupReport#38]
When running dupreport with the -c option I get the following:  This happens with warnoncollect set to either true of false.  The warning email does get sent before crash.

~~~
Traceback (most recent call last):
  File "./dupReport.py", line 217, in <module>
    globs.outServer.sendEmail(msgHtml, msgText)
NameError: name 'msgHtml' is not defined
~~~

Temporary fix was add the "and not globs.opts['collect']:" on line 210 and 214.

~~~
    # Do we need to send output to file(s)?
    if globs.opts['file'] and not globs.opts['collect']:
        report.sendReportToFile(msgHtml, msgText, msgCsv)

    # Are we forbidden from sending report to email?
    if not globs.opts['nomail'] and not globs.opts['collect']:
        globs.outServer.sendEmail(msgHtml, msgText)
~~~

This corrects the error with both email and file creation.

**Comment by dcurrey** [comment]
Another small issue is my error warning is being cut off with only one line.

~~~
A connection attempt failed because the connected party did
~~~

Possible fix in drmail.py line  63
('failed', 'Failed: .*', re.MULTILINE|re.DOTALL, 1),

Now shows:

------------------------------------------------------------------------------------------

Failed: A connection attempt failed because the connected party did not properly respond after a period of time or established connection failed because connected host has failed to respond Details: System.Net.Sockets.SocketException (0x80004005): A connection attempt failed because the connected party did not properly respond after a period of time or established connection failed because connected host has failed to respond at Duplicati.Library.Main.BackendManager.List() at Duplicati.Library.Main.Operation.FilelistProcessor.RemoteListAnalysis(BackendManager backend Options options LocalDatabase database IBackendWriter log String protectedfile) at Duplicati.Library.Main.Operation.RepairHandler.RunRepairRemote() at Duplicati.Library.Main.Operation.RepairHandler.Run(IFilter filter) at Duplicati.Library.Main.Operation.BackupHandler.PreBackupVerify(BackendManager backend String protectedfile) at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources IFilter filter) at Duplicati.Library.Main.Controller.c__DisplayClass16_0.b__0(BackupResults result) at Duplicati.Library.Main.Controller.RunAction[T](T result String[]& paths IFilter& filter Action`1 method)

--------------------------------------------------------------------------------------------
edit:  format

**Comment by HandyGuySoftware** [comment]
Hmmm. Weird. Made the proposed fix and pushed to GH. See if that works better.

**Comment by dcurrey** [comment]
Seem everything is now working with issue 38.
