### ISSUE TITLE
Repeat legend column for every job (enhancement)

### ISSUE THREAD

**Issue by mr-flibble** [HandyGuySoftware/dupReport#39]
Hello, sorry for bother with another "issue" :)  This time it's an idea for a new feature 

I run a report once every 5 days, so table is pretty long and I have a problem remembering which column is what. ..

What do you think about option to repeating the line containing "Data, Errors, Files ..." after the name of each backup job? I think it would certainly improve readability.

**Comment by HandyGuySoftware** [comment]
That shouldn't be too hard to figure out. I'll look into it.

**Comment by HandyGuySoftware** [comment]
@mr-flibble I added a 'repeatheaders' option in the [reports] section. Run the program once to initialize the option. 'true' will repeat headers for each section (as per your suggestion). 'false' prints headers at the top of the report (as per the old behavior). Have a look and let me know if that's what you had in mind.

**Comment by mr-flibble** [comment]
Thanks !!! :-)
This is exactly what I want, now I can finally figure out in the columns :)


![image](https://user-images.githubusercontent.com/5197625/34035416-3f7602be-e182-11e7-9d2b-3e3c6847e201.png)

**Comment by HandyGuySoftware** [comment]
Added to 2.1.0 beta.
