### ISSUE TITLE
Remove emails from database that are no longer on server.

### ISSUE THREAD

**Issue by dcurrey** [HandyGuySoftware/dupReport#42]
Need a way to purge the old emails out the database that are no longer available on the email server.

This is what I was thinking short of having dupreport remove seen emails itself after collect.     Not sure I would like that option myself.

Here is what I am currently testing.

Added another column to the emails database table for an emailseen flag.   Simple 1 for seen 0 for not seen would do.

Have a new setting purgdbemail set to false added to options

At the start of email collect check you update the status to 0 for all emails.
When an email is first seen you just add it to the database with the emailseen = 1.
Email is already in database you update emailseen back to 1.
At end of run anything not added or seen at this point should still be 0.
If the purgedbemail is false nothing else happens.  If true you go and delete all email entries in database where emailseen=0.   

This should keep the database at minimum size and in sync with email folder.

Any thoughts on this or maybe a better way of doing it?

**Comment by HandyGuySoftware** [comment]
I was thinking about something like this a few days ago as I've seen my running time stats slowly rising. But since I never purge my email server I didn't pursue it. Going to fix your line length issue tonight, then need to fix a bug I found in the bydest & bysource reports. After that I can look at mr-flibble's latest suggestion then this. Good idea.

**Comment by dcurrey** [comment]
Cool let me know if you want to see any of the code I have.   I think I only made like 10 minor changes in 3 files.

**Comment by HandyGuySoftware** [comment]
Pushed a new commit to Beta to add this feature. I followed the basic logic you laid out with a couple of changes. Added the ability to specify on command line (-p) or in .rc file ([main] purgedb). This allows you to purge once or all the time. Also added a database compression call in the final purge routine. Evidently, SQLite doesn't automatically compact a database, you have to do it yourself.

Check it out and let me know if this covers it.

**Comment by dcurrey** [comment]
Seem to run correctly on my test server.

Nice catch on the database not compacting.
