### ISSUE TITLE
Add email display name variable

### ISSUE THREAD

**Issue by ninja6o4** [HandyGuySoftware/dupReport#67]
It would be lovely if we could write a custom display name on summary report emails, instead of it defaulting to the email address, e.g.:

> Duplicati Summary Report <logs@mydomain.com>

instead of just:

> logs@mydomain.com

**Comment by HandyGuySoftware** [comment]
Had a light afternoon so I added this in. Updated to GitHub beta branch. Check it out and let me know what you think.

**Comment by HandyGuySoftware** [comment]
Sorry, I probably should explain how it works. Added an `outsendername=` option in the [outgoing] section of the .rc file. If it's not there, dR will add it the next time it is run. If you put a "friendly name" for this option, for example `outsendername = dupReport Summary Emails` it will add that to the outgoing email. If you leave it blank it will just use the sender's email address.

**Comment by dcurrey** [comment]
You can already do this.

Change the .rc outsender line to 
outsender = Duplicata Summary Report <logs.mydomain.com>

edit:  looks like you changed to code already.

**Comment by HandyGuySoftware** [comment]
@dcurrey: Brilliant! I never even thought of doing it that way. I don't think this will break anything else that requires only an email address, but I'll look through the code to double-check. Nice catch!

So now to decide, should I leave the new option in or just point people to your method for adding in a friendly name?

**Comment by HandyGuySoftware** [comment]
Added to 2.1.0 Beta.

**Comment by HandyGuySoftware** [comment]
Backed out this option in favor of method proposed in issue #68.
