### ISSUE TITLE
Send to multiple email addresses

### ISSUE THREAD

**Issue by dcurrey** [HandyGuySoftware/dupReport#68]
Add the option to send to multiple email addresses.

This simple *yet not fully tested" will allow you to send to multiple email addresses

Change dremail.py line 467 to
~~~
self.server.sendmail(sender, receiver.split(','), msg.as_string().encode('utf-8'))
~~~

Then in the .rc file set
~~~
outreceiver = email1@mydomain.com, email2@mydomain.com
~~~

This line will allso accept the form of "User Name <email@mydomain.com> , User 2 <email2@mydomain.com>"

I havn't checked this with any error emails or source-dest specific settings.   Just wanted to see what you think.

**Comment by HandyGuySoftware** [comment]
I think it looks pretty cool. It may be a couple of days before I can fully test it, but I will definitely check it out. Thanks!

**Comment by HandyGuySoftware** [comment]
Testing checked out. Backed out code for #67 and handled both in this fix. 

Latest code pushed to GitHub. Unless there are any show-stoppers in the next week I'm going to release 2.1.0 and start working on 2.1.1 (better email processing). **Last call for new features/bugs**.

Great find, @dcurrey ! Thanks!
