### ISSUE TITLE
Logging doesn't flush to file

### ISSUE THREAD

**Issue by davegold24** [HandyGuySoftware/dupReport#8]
Brand new to dupreport, and i noticed that it doesn't flush to the log file until the end of the job.

I'm running it on CentOS7, installed Python3.4, did the initial config, and am now running it.

It ended up timing out with an SMTP error, but in the 5 minutes while I waited, nothing was written to the log.

Unfortunately, while I can sort of read python, I can't write it. I can google, and the following may help:
https://stackoverflow.com/questions/39396393/logging-how-to-control-the-times-in-which-flush-to-log-file

**Comment by HandyGuySoftware** [comment]
Added file flush() call during log writing. Should flush buffer after every write function.

**Comment by HandyGuySoftware** [comment]
davegold24, the dupReport.py file in the 'beta' branch adds a file flush command after every log write. Hopefully this should address the timeout problem. It won't do any writes while it's waiting for the SMTP timeout, but at least you will capture any log info up to that point.

**Comment by dgold9670** [comment]
I ended up figuring out the timeout cause--incorrect port number for tls for my email smtp server. Thanks for the update.
