### ISSUE TITLE
Handling of differing date formats

### ISSUE THREAD

**Issue by ninja6o4** [HandyGuySoftware/dupReport#81]
This probably isn't encountered in the US, but in Canada, computers often are seen with two date formats: MM-DD-YYYY if it was left as Windows default of "English (US)" or YYYY-MM-DD if someone took the time to correctly set it to "English (Canada)".

I just added a new computer that is set to English (Canada), and this mucks with dupReport. I am sure I can change it for this PC, but at some point I will run into a client that wants it left in Canadian formatting, and it will break my dupReport. 

The only solution I can come up with is to run two different dupReports: one for US date formatting, one for Canuck date formatting. Any thoughts on this? Does dupReport gracefully handle an incorrect date format (log/skip it)?

**Comment by HandyGuySoftware** [comment]
You can alter the date and time formats used by the program in the .rc file under [main]dateformat= . Changing this value will allow you to use different date formats for all your backups. The readme file will show you all the valid formats under the "[main] section" description.

If you have a situation where you are using dupReport to collect emails from multiple systems, each with a different date format, you can set the dateformat= value on a per-backup basis. See the readme file under the "[source-destination] Sections" section.

Let me know if this helps your situation.

**Comment by ninja6o4** [comment]
Thanks, this should be ideal! However, when I tried it, I got this error (running 2.2 pre-prod):

```
Traceback (most recent call last):
  File "dupReport.py", line 214, in <module>
    nxtMsg = globs.inServer.processNextMessage()
  File "C:\dupReport-2.1.0\dremail.py", line 437, in processNextMessage
    globs.log.write(3, 'endTimeStamp=[{}] beginTimeStamp=[{}]'.format(drdatetime.fromTimestamp(dateParts['endTimestamp']), drdatetime.fromTimestamp(dateParts['beginTimestamp'])))
  File "C:\dupReport-2.1.0\drdatetime.py", line 134, in fromTimestamp
    dt = datetime.datetime.fromtimestamp(float(ts))
TypeError: float() argument must be a string or a number, not 'NoneType'
```

Log indicates that it does find and parse the email correctly.
Last few lines of the log:

```
, Details: .*, 24, 1
EmailServer.searchMesagePart(DeletedFiles: 0

DeletedFolders: 0

ModifiedFiles: 0

ExaminedFiles: 1310

OpenedFiles: 1310

AddedFiles: 1310

SizeOfModifiedFiles: 0

SizeOfAddedFiles: 413427324

SizeOfExaminedFiles: 413427324

SizeOfOpenedFiles: 413427324

NotProcessedFiles: 0

AddedFolders: 1030

TooLargeFiles: 0

FilesWithError: 0

ModifiedFolders: 0

ModifiedSymlinks: 0

AddedSymlinks: 0

DeletedSymlinks: 0

PartialBackup: False

Dryrun: False

MainOperation: Backup

ParsedResult: Success

VerboseOutput: False

VerboseErrors: False

EndTime: 2018-01-25 10:03:11 PM

BeginTime: 2018-01-25 10:01:48 PM

Duration: 00:01:22.4268784

Messages: [

    No remote filesets were deleted

]

Warnings: []

Errors: []

, Failed: .*, 24, 1
statusParts['failed']=[]
options.getRcSectionDateTimeFmt(Sam_10, BackupServer)
drDateTime.toTimestamp(2018-01-25 10:03:11 PM, YYYY/MM/DD, HH:MM:SS, -28800)
drDateTime.toTimestamp(2018-01-25 10:01:48 PM, YYYY/MM/DD, HH:MM:SS, -28800)
drdatetime.fromTimestamp(None, MM/DD/YYYY, HH:MM:SS)
```

**Comment by HandyGuySoftware** [comment]
Can you run in verbose mode (-v 3 on the command line)? Then, after it crashes again paste the last 30 or so lines from the log file. Then we can trace what's happening.

**Comment by HandyGuySoftware** [comment]
Also let me know what you have for the dateformat= lines in the [main] section and the dateformat= lines from any [source-destination] sections you may have.

**Comment by ninja6o4** [comment]
That was the verbose log..
```
[main]
dateformat = MM/DD/YYYY
timeformat = HH:MM:SS
```
```
[Sam_10-BackupServer]
dateformat = YYYY/MM/DD
timeformat = HH:MM:SS
```

**Comment by HandyGuySoftware** [comment]
I just added some debug code to the Issue_80 branch to see if I can trace this. Download that branch, run it again, post the same tail of the log, and we'll see what happens.

**Comment by ninja6o4** [comment]
Done.. Different error now:
```
Traceback (most recent call last):
  File "dupReport.py", line 214, in <module>
    nxtMsg = globs.inServer.processNextMessage()
  File "C:\dupReport-2.1.0\dremail.py", line 412, in processNextMessage
    dateParts['endTimestamp'] = self.parenOrRaw(statusParts['endTimeStr'], df = dt, tf = tm, tz = msgParts['timezone'])
  File "C:\dupReport-2.1.0\dremail.py", line 241, in parenOrRaw
    retval = drdatetime.toTimestamp(val, dfmt=df, tfmt=tf, utcOffset=tz)
  File "C:\dupReport-2.1.0\drdatetime.py", line 106, in toTimestamp
    ts = datetime.datetime(year, month, day, hour, minute, second).timestamp()
ValueError: month must be in 1..12
```

Log craps out on a different email. for several pages prior it just repeats this same backup job's output before it craps out at the end shown here:
```
Errors: []



, Details: .*, 24, 1
EmailServer.searchMesagePart(DeletedFiles: 0

DeletedFolders: 0

ModifiedFiles: 0

ExaminedFiles: 23320

OpenedFiles: 23320

AddedFiles: 23309

SizeOfModifiedFiles: 0

SizeOfAddedFiles: 7153676948

SizeOfExaminedFiles: 7153676948

SizeOfOpenedFiles: 7153676948

NotProcessedFiles: 0

AddedFolders: 6733

TooLargeFiles: 0

FilesWithError: 11

ModifiedFolders: 0

ModifiedSymlinks: 0

AddedSymlinks: 2

DeletedSymlinks: 0

PartialBackup: False

Dryrun: False

MainOperation: Backup

ParsedResult: Error

VerboseOutput: False

VerboseErrors: False

EndTime: 18/01/2018 10:09:50 AM

BeginTime: 18/01/2018 6:52:32 AM

Duration: 03:17:18.5048532

Messages: [

    No remote filesets were deleted

]

Warnings: [

    Failed to process path: C:\Users\Theresa\ntuser.dat => The process cannot access the file 'C:\Users\Theresa\ntuser.dat' because it is being used by another process.,

]

Errors: []



, Failed: .*, 24, 1
statusParts['failed']=[]
options.getRcSectionDateTimeFmt(123 Surgery Centre _ Back Room, Backup Server)
dremail.parenOrRaw(18/01/2018 10:09:50 AM, MM/DD/YYYY, HH:MM:SS, -28800)
drDateTime.toTimestamp(18/01/2018 10:09:50 AM, MM/DD/YYYY, HH:MM:SS, -28800)
```

**Comment by HandyGuySoftware** [comment]
`dremail.parenOrRaw(18/01/2018 10:09:50 AM, MM/DD/YYYY, HH:MM:SS, -28800)
drDateTime.toTimestamp(18/01/2018 10:09:50 AM, MM/DD/YYYY, HH:MM:SS, -28800)`

Your dates are coming in as "DD/MM/YYYY" but your datespec is "MM/DD/YYYY". If all your dates from all backup jobs are "DD/MM/YYYY" you need to change the date format spec in the [main] section of the .rc file to:
`dateformat=DD/MM/YYYY`
If you have different date formats in different jobs you can set up a specific .rc section for [123 Surgery Centre _ Back Room-Backup Server]. In that section you can specify 
`dateformat=DD/MM/YYYY`
That should address the problem. dupReport doesn't add source-destination sections automatically, so you'll have to edit the .rc file directly and add that. See the readme file under [[source-destination] sections](https://github.com/HandyGuySoftware/dupReport/tree/pre_prod#source-destination-sections)  for more details.

Also, I noticed that there are spaces in your source and destination names. Not sure if this is an artifact of the way they are printed, but dupReport chokes on spaces in source & destination names. You'll need to remove all spaces in the Duplicati job names for it to parse properly.

Let me know how that goes.

**Comment by ninja6o4** [comment]
lol a third date format.. (facepalm)
I do have spacing in the names, but using dcurrey's regex to capture it properly. So far it doesn't seem to be directly causing any issues

OK I am back to the original error now, tail log is longer:
```
, Failed: .*, 24, 1
statusParts['failed']=[]
options.getRcSectionDateTimeFmt(Sam_10, BackupServer)
dremail.parenOrRaw(2018-01-25 10:03:11 PM, YYYY/MM/DD, HH:MM:SS, -28800)
drDateTime.toTimestamp(2018-01-25 10:03:11 PM, YYYY/MM/DD, HH:MM:SS, -28800)
retval=[None]
dremail.parenOrRaw(2018-01-25 10:01:48 PM, YYYY/MM/DD, HH:MM:SS, -28800)
drDateTime.toTimestamp(2018-01-25 10:01:48 PM, YYYY/MM/DD, HH:MM:SS, -28800)
retval=[None]
dremail.parenOrRaw(0, None, None, None)
retval=[0]
dremail.parenOrRaw(413427324, None, None, None)
retval=[413427324]
dremail.parenOrRaw(413427324, None, None, None)
retval=[413427324]
dremail.parenOrRaw(413427324, None, None, None)
retval=[413427324]
drdatetime.fromTimestamp(None, MM/DD/YYYY, HH:MM:SS)
```

**Comment by HandyGuySoftware** [comment]
```
dremail.parenOrRaw(2018-01-25 10:03:11 PM, YYYY/MM/DD, HH:MM:SS, -28800)
drDateTime.toTimestamp(2018-01-25 10:03:11 PM, YYYY/MM/DD, HH:MM:SS, -28800)
```
Interesting. Same issue here: dates are coming in as YYYY-MM-DD but datespec is YYYY/MM/DD. Is the date in the original email shown as YYYY-MM-DD or is that being generated by dR somewhere?

**Comment by HandyGuySoftware** [comment]
Can you post the [main] section and any [source-destination] sections from your .rc file?

**Comment by ninja6o4** [comment]
oh geez, sorry about that! so easy to overlook that.
OK corrected the custom format to - instead of / and it works!
Not sure if it's possible, but would be nice if dupReport could parse either delimiter, only focusing on the position of the MDY fields. 
For example, setting dateformat = MM/DD/YYYY will try either MM/DD/YYYY first, then MM-DD-YYYY before giving up.
Additionally, rather than crashing out, cuz this is such an easy thing to overlook, could we have a graceful error like "Date/Time formatting appears to be incorrect, please verify your date/time settings vs. the .rc file"?

**Comment by HandyGuySoftware** [comment]
Both good suggestions. I'll take a look at implementing both. So is the program working for you now?
