### ISSUE TITLE
Better error handling of date/time formats.

### ISSUE THREAD

**Issue by HandyGuySoftware** [HandyGuySoftware/dupReport#83]
from @ninja604:
Not sure if it's possible, but would be nice if dupReport could parse either delimiter, only focusing on the position of the MDY fields.
For example, setting dateformat = MM/DD/YYYY will try either either MM/DD/YYYY or MM-DD-YYYY before giving up.
Additionally, rather than crashing out, cuz this is such an easy thing to overlook, could we have a graceful error like "Date/Time formatting appears to be incorrect, please verify your date/time settings vs. the .rc file"?

**Comment by ninja6o4** [comment]
Adding to this - might be handy to log which email was the problem for easy resolution. e.g.
```
Received: date/time
Subject: backup report
dupReport backup pair: <source>-<dest>
Date field received: 01/27/2018
Date format expected (from .rc): YYYY/MM/DD
```

**Comment by HandyGuySoftware** [comment]
@ninja6o4, I tried to address your suggestions, and went part way. Here's what I have:

1. I opted not to use "fuzzy logic" to try to guess which format the user _meant_ to use, rather than the one they _did_ use. While this would be a little easier for the user, so much depends on the proper date format specification that I imagined more than one scenario where fuzzing the date spec up front sent a cascading wave of badness through later stages of the program.

1.  However, I did update the error handling portion of the date processing to be much more descriptive of what has happened and to exit gracefully rather than abruptly crash. If such a situation happens the user will see this on stderr:
```
Date/time format specification mismatch. See log file for details. Exiting program.
SystemExit: 1
```
And here's what will be at the bottom of the log file:
```
Error creating timestamp: dateformat=YYYY/MM/DD year=10 month=30 day=2017 hour=12 minute=30 second=29
This is likely caused by an email using a different date or time format than expected, particuly if you're collecting emails from multiple locations or time zones.
Please check the 'dateformat=' and 'timeformat=' value(s) in the [main] section and any [<source>-<destination>] sections of your .rc file for accuracy.
Closing everything...
Closing inbound email server...
Closing outbound email server...
Closing database file...
Database.dbClose(): Closing database object.
Closing log file...
```
3. Finally, the date/time parsing routines are isolated form the rest of the program in such a way that it's impossible to know at crash time the header info from the email currently being processed. Object-oriented programming is both a blessing and a curse that way :-(. However, I realized that nowhere in the log is a concise recap of the basic information from the email currently being processed (as you suggested.) Therefore, I added some debug statements to the log (viewable at level 1 so it will always be there) to provide this basic information:
```
***** Next Message: Date=[Mon, 30 Oct 2017 07:30:51 -0500] Subject=[Duplicati Backup report for Sys1-Sys2] Message-Id=[<M2O5E13IQ2U4.C3NK6VR1BUH41@Sys1>]
```
The data is also offset by an empty line in the log to make it more visible to the reader.

While not exactly what you were looking for, I hope these changes are an acceptable compromise to help avoid the debugging trail we went through the last couple of days. I have uploaded the new code to the [Issue_83 branch on GitHub](https://github.com/HandyGuySoftware/dupReport/tree/Issue_83). Have a look, give it a spin, and let me know if that's OK (or if you have any other suggestions).

**Comment by HandyGuySoftware** [comment]
@ninja6o4: OK, cancel that last message. I kept thinking about it and think I've found a way to fuzz the date delimiters to be more forgiving without causing downstream trouble. As long as the day, month, and year parts are in the right order, dR should now be able to parse them with any delimiter (i.e. '/', '-', or '.'). If the parts are out of order (e.g., spec is 'MM-DD-YY' and the input is 'DD-MM-YY' the results are undefined. The error handling I put in last night _should_ catch it, but not sure if I've handled all cases.

Unfortunately, I have a limited data set to test with. Can you download and test the latest [Issue_83 branch](https://github.com/HandyGuySoftware/dupReport/tree/Issue_83) and let me know how it works for you?

Thanks

**Comment by ninja6o4** [comment]
I tried it and can confirm that it worked in my test case! Didn't crash or complain, processed the erroneously formatted date. Thanks for adding this!

**Comment by HandyGuySoftware** [comment]
No problem! I'll post the patches to the pre_prod branch tonight. Thanks for the help with this.
